"""ORM models.

Importing this package registers every table on ``Base.metadata``. Alembic
autogenerate diffs against that metadata, so a model this module does not import is
a model Alembic silently omits from the migration.
"""

from __future__ import annotations

from app.models.alerts import Alert, AlertEvidence
from app.models.dimensions import (
    DimAsset,
    DimBenchmark,
    DimIssuer,
    DimOwnProduct,
    DimPerpContract,
    DimPool,
    DimTheme,
    DimUnderlying,
    DimUser,
    DimVenue,
    ThemeMap,
)
from app.models.editions import Edition, EditionArtifact, EditionRevision
from app.models.enums import (
    ALERT_TRANSITIONS,
    AlertActionType,
    AlertSeverity,
    AlertState,
    AlertStatus,
    AssetClass,
    AuthMode,
    CLOSED_ALERT_STATES,
    CandidateDecision,
    CandidateStage,
    CoverageState,
    DataGapKind,
    DataGapStatus,
    DetectorFamily,
    EditionKind,
    EditionStatus,
    EntityType,
    FetchStatus,
    IN_SCOPE_TIERS,
    MappingStatus,
    OPEN_ALERT_STATES,
    PUBLISHABLE_VERIFICATION,
    ResearchTaskStatus,
    RwaTier,
    SourceStatus,
    UserRole,
    VenueType,
    VerificationStatus,
)
from app.models.facts import (
    FactAssetSnapshot,
    FactCategorySnapshot,
    FactIssuerPlatformSnapshot,
    FactIssuerSnapshot,
    FactLaunchWindowSnapshot,
    FactPairSnapshot,
    FactPerpContractSnapshot,
    FactPerpVenueSnapshot,
    FactPoolSnapshot,
    FactUnderlyingReference,
    FactVenueSnapshot,
)
from app.models.operations import (
    BaselineSnapshot,
    FetchLog,
    ReportArtifact,
    SourceRegistry,
    UnderlyingMap,
)
from app.models.workflow import (
    AlertAction,
    AuditLog,
    CandidateGateLog,
    DataGap,
    IssuanceCandidate,
    ProductCoverage,
    ResearchTask,
)

__all__ = [
    "ALERT_TRANSITIONS",
    "CLOSED_ALERT_STATES",
    "IN_SCOPE_TIERS",
    "OPEN_ALERT_STATES",
    "PUBLISHABLE_VERIFICATION",
    "Alert",
    "AlertAction",
    "AlertActionType",
    "AlertEvidence",
    "AlertSeverity",
    "AlertState",
    "AlertStatus",
    "AssetClass",
    "AuditLog",
    "AuthMode",
    "BaselineSnapshot",
    "CandidateDecision",
    "CandidateGateLog",
    "CandidateStage",
    "CoverageState",
    "DataGap",
    "DataGapKind",
    "DataGapStatus",
    "DetectorFamily",
    "DimAsset",
    "DimBenchmark",
    "DimIssuer",
    "DimOwnProduct",
    "DimPerpContract",
    "DimPool",
    "DimTheme",
    "DimUnderlying",
    "DimUser",
    "DimVenue",
    "Edition",
    "EditionArtifact",
    "EditionKind",
    "EditionRevision",
    "EditionStatus",
    "EntityType",
    "FactAssetSnapshot",
    "FactCategorySnapshot",
    "FactIssuerPlatformSnapshot",
    "FactIssuerSnapshot",
    "FactLaunchWindowSnapshot",
    "FactPairSnapshot",
    "FactPerpContractSnapshot",
    "FactPerpVenueSnapshot",
    "FactPoolSnapshot",
    "FactUnderlyingReference",
    "FactVenueSnapshot",
    "FetchLog",
    "FetchStatus",
    "IssuanceCandidate",
    "MappingStatus",
    "ProductCoverage",
    "ReportArtifact",
    "ResearchTask",
    "ResearchTaskStatus",
    "RwaTier",
    "SourceRegistry",
    "SourceStatus",
    "ThemeMap",
    "UnderlyingMap",
    "UserRole",
    "VenueType",
    "VerificationStatus",
]
