"""initial schema

Revision ID: 8e37454e71a4
Revises:
Create Date: 2026-08-17 18:19:02.944957

"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "8e37454e71a4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("dedup_key", sa.String(length=255), nullable=False),
        sa.Column("detector", sa.String(length=64), nullable=False),
        sa.Column(
            "family",
            sa.Enum(
                "cross_sectional",
                "time_series",
                name="detectorfamily",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "entity_type",
            sa.Enum(
                "asset",
                "pair",
                "pool",
                "venue",
                "issuer",
                "underlying",
                "perp_contract",
                "perp_venue",
                "theme",
                "category",
                name="entitytype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.String(length=96), nullable=False),
        sa.Column(
            "metric_scope",
            sa.Enum(
                "spot_market_cap",
                "spot_volume",
                "dex_liquidity",
                "perp_volume",
                "perp_oi",
                name="metricscope",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "market_session",
            sa.Enum(
                "rth",
                "pre",
                "ah",
                "closed_weekday",
                "closed_weekend",
                "closed_holiday",
                name="marketsession",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "low",
                "medium",
                "high",
                "critical",
                name="alertseverity",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "tentative",
                "confirmed",
                "resolved",
                name="alertstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("headline_zh", sa.Text(), nullable=False),
        sa.Column("headline_en", sa.Text(), nullable=True),
        sa.Column("first_seen_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alert", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_alert_dedup_key"), ["dedup_key"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alert_detector"), ["detector"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alert_entity_id"), ["entity_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_alert_family"), ["family"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_alert_first_seen_ts"), ["first_seen_ts"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alert_last_seen_ts"), ["last_seen_ts"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alert_severity"), ["severity"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_alert_status"), ["status"], unique=False)

    op.create_table(
        "baseline_snapshot",
        sa.Column(
            "entity_type",
            sa.Enum(
                "asset",
                "pair",
                "pool",
                "venue",
                "issuer",
                "underlying",
                "perp_contract",
                "perp_venue",
                "theme",
                "category",
                name="entitytype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.String(length=96), nullable=False),
        sa.Column(
            "metric_scope",
            sa.Enum(
                "spot_market_cap",
                "spot_volume",
                "dex_liquidity",
                "perp_volume",
                "perp_oi",
                name="metricscope",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "market_session",
            sa.Enum(
                "rth",
                "pre",
                "ah",
                "closed_weekday",
                "closed_weekend",
                "closed_holiday",
                name="marketsession",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("median", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("mad", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column("is_alertable", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint(
            "entity_type", "entity_id", "metric_scope", "market_session", "snapshot_ts"
        ),
    )
    op.create_table(
        "dim_benchmark",
        sa.Column("benchmark_id", sa.String(length=96), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("benchmark_id"),
    )
    op.create_table(
        "dim_issuer",
        sa.Column("issuer_id", sa.String(length=96), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("official_product_count", sa.Integer(), nullable=True),
        sa.Column("official_url", sa.String(length=512), nullable=True),
        sa.Column("legal_structure_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("issuer_id"),
    )
    op.create_table(
        "dim_theme",
        sa.Column("theme_id", sa.String(length=96), nullable=False),
        sa.Column("name_zh", sa.String(length=128), nullable=False),
        sa.Column("name_en", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("theme_id"),
    )
    op.create_table(
        "dim_venue",
        sa.Column("venue_id", sa.String(length=96), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "venue_type",
            sa.Enum(
                "cex", "dex", "perp_dex", name="venuetype", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("chain", sa.String(length=64), nullable=True),
        sa.Column("aliases", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("venue_id"),
    )
    with op.batch_alter_table("dim_venue", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dim_venue_venue_type"), ["venue_type"], unique=False
        )

    op.create_table(
        "fact_category_snapshot",
        sa.Column("category_id", sa.String(length=96), nullable=False),
        sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("asset_count", sa.Integer(), nullable=True),
        sa.Column("market_cap", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("vol_24h", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("is_additive", sa.Boolean(), nullable=False),
        sa.Column(
            "market_session",
            sa.Enum(
                "rth",
                "pre",
                "ah",
                "closed_weekday",
                "closed_weekend",
                "closed_holiday",
                name="marketsession",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_carried_forward", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("category_id", "snapshot_ts"),
    )
    with op.batch_alter_table("fact_category_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fact_category_snapshot_market_session"),
            ["market_session"],
            unique=False,
        )

    op.create_table(
        "fact_perp_venue_snapshot",
        sa.Column("exchange", sa.String(length=64), nullable=False),
        sa.Column("perp_dex", sa.String(length=64), nullable=False),
        sa.Column("segment", sa.String(length=32), nullable=False),
        sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("vol_24h", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column(
            "open_interest_usd", sa.Numeric(precision=30, scale=8), nullable=True
        ),
        sa.Column("symbol_count", sa.Integer(), nullable=True),
        sa.Column(
            "market_session",
            sa.Enum(
                "rth",
                "pre",
                "ah",
                "closed_weekday",
                "closed_weekend",
                "closed_holiday",
                name="marketsession",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_carried_forward", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("exchange", "perp_dex", "segment", "snapshot_ts"),
    )
    with op.batch_alter_table("fact_perp_venue_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fact_perp_venue_snapshot_market_session"),
            ["market_session"],
            unique=False,
        )

    op.create_table(
        "report_artifact",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("report_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("report_format", sa.String(length=16), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=True),
        sa.Column("storage_key", sa.String(length=512), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "report_date", "report_format", name="uq_report_artifact_date_format"
        ),
    )
    with op.batch_alter_table("report_artifact", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_report_artifact_report_date"), ["report_date"], unique=False
        )

    op.create_table(
        "source_registry",
        sa.Column("source_id", sa.String(length=96), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("base_url", sa.String(length=512), nullable=True),
        sa.Column(
            "auth_mode",
            sa.Enum(
                "public",
                "api_key",
                "challenge",
                name="authmode",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "planned",
                "reference_only",
                "disabled",
                name="sourcestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("cadence_minutes", sa.Integer(), nullable=True),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=True),
        sa.Column("provides_scopes", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("source_id"),
    )
    with op.batch_alter_table("source_registry", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_registry_status"), ["status"], unique=False
        )

    op.create_table(
        "alert_evidence",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "alert_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rule_name", sa.String(length=64), nullable=False),
        sa.Column("observed_value", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("baseline_median", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("baseline_mad", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("robust_z", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=True),
        sa.Column(
            "market_session",
            sa.Enum(
                "rth",
                "pre",
                "ah",
                "closed_weekday",
                "closed_weekend",
                "closed_holiday",
                name="marketsession",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("peer_count", sa.Integer(), nullable=True),
        sa.Column("extra_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["alert_id"], ["alert.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alert_evidence", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_alert_evidence_alert_id"), ["alert_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alert_evidence_snapshot_ts"), ["snapshot_ts"], unique=False
        )

    op.create_table(
        "dim_underlying",
        sa.Column("underlying_id", sa.String(length=96), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "asset_class",
            sa.Enum(
                "equity",
                "etf",
                "fund",
                "commodity",
                "fx",
                "index",
                "pre_ipo",
                name="assetclass",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("region", sa.String(length=16), nullable=True),
        sa.Column("isin", sa.String(length=24), nullable=True),
        sa.Column("is_pre_ipo", sa.Boolean(), nullable=False),
        sa.Column("theme_id", sa.String(length=96), nullable=True),
        sa.Column("benchmark_id", sa.String(length=96), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["benchmark_id"],
            ["dim_benchmark.benchmark_id"],
        ),
        sa.ForeignKeyConstraint(
            ["theme_id"],
            ["dim_theme.theme_id"],
        ),
        sa.PrimaryKeyConstraint("underlying_id"),
    )
    with op.batch_alter_table("dim_underlying", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dim_underlying_benchmark_id"), ["benchmark_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dim_underlying_theme_id"), ["theme_id"], unique=False
        )

    op.create_table(
        "fact_venue_snapshot",
        sa.Column("venue_id", sa.String(length=96), nullable=False),
        sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_vol_24h", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("adjusted_vol_24h", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("share", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("pair_count", sa.Integer(), nullable=True),
        sa.Column("underlying_count", sa.Integer(), nullable=True),
        sa.Column(
            "market_session",
            sa.Enum(
                "rth",
                "pre",
                "ah",
                "closed_weekday",
                "closed_weekend",
                "closed_holiday",
                name="marketsession",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_carried_forward", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["dim_venue.venue_id"],
        ),
        sa.PrimaryKeyConstraint("venue_id", "snapshot_ts"),
    )
    with op.batch_alter_table("fact_venue_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fact_venue_snapshot_market_session"),
            ["market_session"],
            unique=False,
        )

    op.create_table(
        "fetch_log",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=96), nullable=False),
        sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("endpoint", sa.String(length=512), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ok",
                "partial",
                "not_verified",
                "rate_limited",
                "error",
                name="fetchstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_registry.source_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fetch_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fetch_log_snapshot_ts"), ["snapshot_ts"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fetch_log_source_id"), ["source_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fetch_log_status"), ["status"], unique=False
        )

    op.create_table(
        "dim_asset",
        sa.Column("asset_id", sa.String(length=96), nullable=False),
        sa.Column("coin_id", sa.String(length=128), nullable=True),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("chain", sa.String(length=64), nullable=True),
        sa.Column("contract_address", sa.String(length=128), nullable=True),
        sa.Column(
            "rwa_tier",
            sa.Enum(
                "core_rwa",
                "rwa_adjacent",
                "synthetic",
                "non_rwa",
                name="rwatier",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("underlying_id", sa.String(length=96), nullable=True),
        sa.Column("issuer_id", sa.String(length=96), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["dim_issuer.issuer_id"],
        ),
        sa.ForeignKeyConstraint(
            ["underlying_id"],
            ["dim_underlying.underlying_id"],
        ),
        sa.PrimaryKeyConstraint("asset_id"),
    )
    with op.batch_alter_table("dim_asset", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dim_asset_coin_id"), ["coin_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dim_asset_issuer_id"), ["issuer_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dim_asset_rwa_tier"), ["rwa_tier"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dim_asset_symbol"), ["symbol"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dim_asset_underlying_id"), ["underlying_id"], unique=False
        )

    op.create_table(
        "dim_perp_contract",
        sa.Column("contract_id", sa.String(length=96), nullable=False),
        sa.Column("exchange", sa.String(length=64), nullable=False),
        sa.Column("perp_dex", sa.String(length=64), nullable=True),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("source_underlying_type", sa.String(length=64), nullable=True),
        sa.Column("analysis_group", sa.String(length=64), nullable=True),
        sa.Column("underlying_id", sa.String(length=96), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["underlying_id"],
            ["dim_underlying.underlying_id"],
        ),
        sa.PrimaryKeyConstraint("contract_id"),
    )
    with op.batch_alter_table("dim_perp_contract", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dim_perp_contract_exchange"), ["exchange"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dim_perp_contract_perp_dex"), ["perp_dex"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dim_perp_contract_symbol"), ["symbol"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dim_perp_contract_underlying_id"),
            ["underlying_id"],
            unique=False,
        )

    op.create_table(
        "underlying_map",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=96), nullable=False),
        sa.Column("source_symbol", sa.String(length=96), nullable=False),
        sa.Column("normalized_symbol", sa.String(length=96), nullable=True),
        sa.Column("underlying_id", sa.String(length=96), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "auto",
                "reviewed",
                "pending_review",
                "rejected",
                name="mappingstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("rule", sa.String(length=96), nullable=True),
        sa.Column("reviewed_by", sa.String(length=96), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["underlying_id"],
            ["dim_underlying.underlying_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_id", "source_symbol", name="uq_underlying_map_source"
        ),
    )
    with op.batch_alter_table("underlying_map", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_underlying_map_source_id"), ["source_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_underlying_map_source_symbol"),
            ["source_symbol"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_underlying_map_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_underlying_map_underlying_id"),
            ["underlying_id"],
            unique=False,
        )

    op.create_table(
        "dim_pool",
        sa.Column("pool_id", sa.String(length=96), nullable=False),
        sa.Column("network", sa.String(length=64), nullable=False),
        sa.Column("dex", sa.String(length=64), nullable=False),
        sa.Column("pool_address", sa.String(length=128), nullable=True),
        sa.Column("base_asset_id", sa.String(length=96), nullable=True),
        sa.Column("quote_token", sa.String(length=64), nullable=True),
        sa.Column("is_canonical_quote", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_asset_id"],
            ["dim_asset.asset_id"],
        ),
        sa.PrimaryKeyConstraint("pool_id"),
    )
    with op.batch_alter_table("dim_pool", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dim_pool_base_asset_id"), ["base_asset_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_dim_pool_dex"), ["dex"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_dim_pool_network"), ["network"], unique=False
        )

    op.create_table(
        "fact_asset_snapshot",
        sa.Column("asset_id", sa.String(length=96), nullable=False),
        sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price_usd", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("market_cap", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("fdv", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("vol_24h", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column(
            "circulating_supply", sa.Numeric(precision=30, scale=8), nullable=True
        ),
        sa.Column("change_24h", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("change_7d", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("change_30d", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column(
            "market_session",
            sa.Enum(
                "rth",
                "pre",
                "ah",
                "closed_weekday",
                "closed_weekend",
                "closed_holiday",
                name="marketsession",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_carried_forward", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["dim_asset.asset_id"],
        ),
        sa.PrimaryKeyConstraint("asset_id", "snapshot_ts"),
    )
    with op.batch_alter_table("fact_asset_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fact_asset_snapshot_market_session"),
            ["market_session"],
            unique=False,
        )

    op.create_table(
        "fact_pair_snapshot",
        sa.Column("asset_id", sa.String(length=96), nullable=False),
        sa.Column("venue_id", sa.String(length=96), nullable=False),
        sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_vol_24h", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("adjusted_vol_24h", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("price_usd", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("spread_pct", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("trust_score", sa.String(length=16), nullable=True),
        sa.Column("is_quality_anomaly", sa.Boolean(), nullable=False),
        sa.Column("is_quality_stale", sa.Boolean(), nullable=False),
        sa.Column(
            "market_session",
            sa.Enum(
                "rth",
                "pre",
                "ah",
                "closed_weekday",
                "closed_weekend",
                "closed_holiday",
                name="marketsession",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_carried_forward", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["dim_asset.asset_id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["dim_venue.venue_id"],
        ),
        sa.PrimaryKeyConstraint("asset_id", "venue_id", "snapshot_ts"),
    )
    with op.batch_alter_table("fact_pair_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fact_pair_snapshot_market_session"),
            ["market_session"],
            unique=False,
        )

    op.create_table(
        "fact_perp_contract_snapshot",
        sa.Column("contract_id", sa.String(length=96), nullable=False),
        sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("vol_24h", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("oi_units", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("oi_usd", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("funding_rate", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("mark_price", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("index_price", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column(
            "market_session",
            sa.Enum(
                "rth",
                "pre",
                "ah",
                "closed_weekday",
                "closed_weekend",
                "closed_holiday",
                name="marketsession",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_carried_forward", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["dim_perp_contract.contract_id"],
        ),
        sa.PrimaryKeyConstraint("contract_id", "snapshot_ts"),
    )
    with op.batch_alter_table("fact_perp_contract_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fact_perp_contract_snapshot_market_session"),
            ["market_session"],
            unique=False,
        )

    op.create_table(
        "fact_pool_snapshot",
        sa.Column("pool_id", sa.String(length=96), nullable=False),
        sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reserve_usd", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("vol_24h", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("buys_24h", sa.Integer(), nullable=True),
        sa.Column("sells_24h", sa.Integer(), nullable=True),
        sa.Column("tx_count_24h", sa.Integer(), nullable=True),
        sa.Column(
            "market_session",
            sa.Enum(
                "rth",
                "pre",
                "ah",
                "closed_weekday",
                "closed_weekend",
                "closed_holiday",
                name="marketsession",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_carried_forward", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pool_id"],
            ["dim_pool.pool_id"],
        ),
        sa.PrimaryKeyConstraint("pool_id", "snapshot_ts"),
    )
    with op.batch_alter_table("fact_pool_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fact_pool_snapshot_market_session"),
            ["market_session"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fact_pool_snapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fact_pool_snapshot_market_session"))

    op.drop_table("fact_pool_snapshot")
    with op.batch_alter_table("fact_perp_contract_snapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fact_perp_contract_snapshot_market_session"))

    op.drop_table("fact_perp_contract_snapshot")
    with op.batch_alter_table("fact_pair_snapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fact_pair_snapshot_market_session"))

    op.drop_table("fact_pair_snapshot")
    with op.batch_alter_table("fact_asset_snapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fact_asset_snapshot_market_session"))

    op.drop_table("fact_asset_snapshot")
    with op.batch_alter_table("dim_pool", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dim_pool_network"))
        batch_op.drop_index(batch_op.f("ix_dim_pool_dex"))
        batch_op.drop_index(batch_op.f("ix_dim_pool_base_asset_id"))

    op.drop_table("dim_pool")
    with op.batch_alter_table("underlying_map", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_underlying_map_underlying_id"))
        batch_op.drop_index(batch_op.f("ix_underlying_map_status"))
        batch_op.drop_index(batch_op.f("ix_underlying_map_source_symbol"))
        batch_op.drop_index(batch_op.f("ix_underlying_map_source_id"))

    op.drop_table("underlying_map")
    with op.batch_alter_table("dim_perp_contract", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dim_perp_contract_underlying_id"))
        batch_op.drop_index(batch_op.f("ix_dim_perp_contract_symbol"))
        batch_op.drop_index(batch_op.f("ix_dim_perp_contract_perp_dex"))
        batch_op.drop_index(batch_op.f("ix_dim_perp_contract_exchange"))

    op.drop_table("dim_perp_contract")
    with op.batch_alter_table("dim_asset", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dim_asset_underlying_id"))
        batch_op.drop_index(batch_op.f("ix_dim_asset_symbol"))
        batch_op.drop_index(batch_op.f("ix_dim_asset_rwa_tier"))
        batch_op.drop_index(batch_op.f("ix_dim_asset_issuer_id"))
        batch_op.drop_index(batch_op.f("ix_dim_asset_coin_id"))

    op.drop_table("dim_asset")
    with op.batch_alter_table("fetch_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fetch_log_status"))
        batch_op.drop_index(batch_op.f("ix_fetch_log_source_id"))
        batch_op.drop_index(batch_op.f("ix_fetch_log_snapshot_ts"))

    op.drop_table("fetch_log")
    with op.batch_alter_table("fact_venue_snapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fact_venue_snapshot_market_session"))

    op.drop_table("fact_venue_snapshot")
    with op.batch_alter_table("dim_underlying", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dim_underlying_theme_id"))
        batch_op.drop_index(batch_op.f("ix_dim_underlying_benchmark_id"))

    op.drop_table("dim_underlying")
    with op.batch_alter_table("alert_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alert_evidence_snapshot_ts"))
        batch_op.drop_index(batch_op.f("ix_alert_evidence_alert_id"))

    op.drop_table("alert_evidence")
    with op.batch_alter_table("source_registry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_registry_status"))

    op.drop_table("source_registry")
    with op.batch_alter_table("report_artifact", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_artifact_report_date"))

    op.drop_table("report_artifact")
    with op.batch_alter_table("fact_perp_venue_snapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fact_perp_venue_snapshot_market_session"))

    op.drop_table("fact_perp_venue_snapshot")
    with op.batch_alter_table("fact_category_snapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fact_category_snapshot_market_session"))

    op.drop_table("fact_category_snapshot")
    with op.batch_alter_table("dim_venue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dim_venue_venue_type"))

    op.drop_table("dim_venue")
    op.drop_table("dim_theme")
    op.drop_table("dim_issuer")
    op.drop_table("dim_benchmark")
    op.drop_table("baseline_snapshot")
    with op.batch_alter_table("alert", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alert_status"))
        batch_op.drop_index(batch_op.f("ix_alert_severity"))
        batch_op.drop_index(batch_op.f("ix_alert_last_seen_ts"))
        batch_op.drop_index(batch_op.f("ix_alert_first_seen_ts"))
        batch_op.drop_index(batch_op.f("ix_alert_family"))
        batch_op.drop_index(batch_op.f("ix_alert_entity_id"))
        batch_op.drop_index(batch_op.f("ix_alert_detector"))
        batch_op.drop_index(batch_op.f("ix_alert_dedup_key"))

    op.drop_table("alert")
    # ### end Alembic commands ###
