"""tradfi reference prices for underlyings

Every other fact table here measures the tokenized wrapper. This one measures the
share itself, which is what turns "the token traded at 232.5" into a statement that
can be right or wrong. It carries no metric scope and is never summed: a price is
none of the five families, and its use is per-underlying comparison.

``price_ts`` is separate from ``snapshot_ts`` on purpose. The underlying is shut for
most of the hours this system collects, so the two differ by days over a weekend, and
a basis computed without comparing them reads a closed market as a mispricing.
``feed`` is stored per row because the free IEX feed and the consolidated tape are
different populations — a series that switches feed changes meaning mid-chart.

Revision ID: e28ffa03520c
Revises: 39488c424eb8
Create Date: 2026-08-18 10:29:34.873661

"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "e28ffa03520c"
down_revision: str | None = "39488c424eb8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fact_underlying_reference",
        sa.Column("underlying_id", sa.String(length=96), nullable=False),
        sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("price_ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column("prev_close", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("change_24h", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("venue_vol_shares", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("feed", sa.String(length=16), nullable=True),
        sa.Column(
            "market_session",
            sa.Enum(
                "rth",
                "pre",
                "ah",
                "closed_weekday",
                "closed_weekend",
                "closed_holiday",
                name="marketsession",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_carried_forward", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["underlying_id"],
            ["dim_underlying.underlying_id"],
        ),
        sa.PrimaryKeyConstraint("underlying_id", "snapshot_ts"),
    )
    with op.batch_alter_table("fact_underlying_reference", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fact_underlying_reference_market_session"),
            ["market_session"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fact_underlying_reference", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fact_underlying_reference_market_session"))

    op.drop_table("fact_underlying_reference")
    # ### end Alembic commands ###
