"""issuer product breadth and platform listings

Issuers publish larger catalogues than any aggregator indexes — Ondo states 443 and
xStocks lists 716, against the ~113 CoinGecko carries — so the issuer's own count is
the denominator of every coverage ratio. ``dim_issuer.official_product_count`` already
held the latest figure; these tables hold the series, so a catalogue growing is
visible as data rather than inferred from a column that was overwritten in place.

``fact_issuer_platform_snapshot`` keeps one row per platform an issuer names, so a
venue appearing for the first time is a new row rather than a count that went up.

Revision ID: 39488c424eb8
Revises: b1c4f0a97d52
Create Date: 2026-08-18 10:20:42.890409

"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "39488c424eb8"
down_revision: str | None = "b1c4f0a97d52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fact_issuer_platform_snapshot",
        sa.Column("issuer_id", sa.String(length=96), nullable=False),
        sa.Column("platform_name", sa.String(length=96), nullable=False),
        sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "market_session",
            sa.Enum(
                "rth",
                "pre",
                "ah",
                "closed_weekday",
                "closed_weekend",
                "closed_holiday",
                name="marketsession",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_carried_forward", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["dim_issuer.issuer_id"],
        ),
        sa.PrimaryKeyConstraint("issuer_id", "platform_name", "snapshot_ts"),
    )
    with op.batch_alter_table("fact_issuer_platform_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fact_issuer_platform_snapshot_market_session"),
            ["market_session"],
            unique=False,
        )

    op.create_table(
        "fact_issuer_snapshot",
        sa.Column("issuer_id", sa.String(length=96), nullable=False),
        sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("official_product_count", sa.Integer(), nullable=True),
        sa.Column("listed_platform_count", sa.Integer(), nullable=True),
        sa.Column(
            "market_session",
            sa.Enum(
                "rth",
                "pre",
                "ah",
                "closed_weekday",
                "closed_weekend",
                "closed_holiday",
                name="marketsession",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_carried_forward", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["dim_issuer.issuer_id"],
        ),
        sa.PrimaryKeyConstraint("issuer_id", "snapshot_ts"),
    )
    with op.batch_alter_table("fact_issuer_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fact_issuer_snapshot_market_session"),
            ["market_session"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fact_issuer_snapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fact_issuer_snapshot_market_session"))

    op.drop_table("fact_issuer_snapshot")
    with op.batch_alter_table("fact_issuer_platform_snapshot", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_fact_issuer_platform_snapshot_market_session")
        )

    op.drop_table("fact_issuer_platform_snapshot")
    # ### end Alembic commands ###
