"""R1 workflow, editions and decision surfaces

The schema behind "detect → verify → explain → act → review". Three groups of table,
plus the columns that turn an alert from a notification into a business object:

* **Workflow** — ``alert_action`` (append-only, one row per transition, note and
  reassignment), ``audit_log``, ``research_task``, ``issuance_candidate`` with its
  ``candidate_gate_log``, ``product_coverage`` and ``data_gap``. None of these are a
  pipeline stage; they read analytics output and never write ``fact_*``.
* **Editions** — ``edition``, ``edition_revision`` and ``edition_artifact``. A frozen
  edition is never updated: a correction writes a numbered revision carrying its
  reason and diff, and the superseded version stays readable. Artifacts hold their
  bytes in the row because production K8s provides no PersistentVolumeClaim.
* **Reference** — ``dim_user`` (someone an alert can be attributed to),
  ``dim_own_product`` (what turns "coverage gap" from an opinion into a join),
  ``theme_map`` (versioned, many-to-many, with an author and a reason) and
  ``fact_launch_window_snapshot`` (a new listing's first 1h/6h/24h, measured from the
  listing moment rather than the top of an hour).

Two backfills deserve stating, because both are claims about existing rows:

``alert.state`` defaults to ``detected`` and ``published_at`` stays null, so every
alert that predates the publication gate is invisible on every surface until a
detector re-fires it and the gate rules on it. The alternative — marking history
``published`` — would put findings that never crossed the gate onto a management
screen, which is the one thing rule 14 exists to prevent. Anything still true is
re-detected on the next scheduled run.

``alert_evidence.verification_status`` defaults to ``verified``. These rows carry an
observed number, and a ``NOT_VERIFIED`` row may not carry a number at all — so
``verified`` is the only one of the five states that is true of them.

Revision ID: f67dceb9867c
Revises: 7d5a1c2e9b04
Create Date: 2026-08-26 17:19:39.332082

"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "f67dceb9867c"
down_revision: str | None = "7d5a1c2e9b04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("entity_kind", sa.String(length=48), nullable=False),
        sa.Column("entity_id", sa.String(length=96), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=96), nullable=True),
        sa.Column("actor_role", sa.String(length=32), nullable=True),
        sa.Column("diff_json", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_log_action"), ["action"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_actor_id"), ["actor_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_entity_id"), ["entity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_entity_kind"), ["entity_kind"], unique=False
        )

    op.create_table(
        "data_gap",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "source_health",
                "entity_coverage",
                "quality_divergence",
                "verification",
                "baseline_health",
                name="datagapkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "assigned",
                "fixed",
                "accepted",
                name="datagapstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("dedup_key", sa.String(length=255), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "asset",
                "pair",
                "pool",
                "venue",
                "issuer",
                "underlying",
                "perp_contract",
                "perp_venue",
                "theme",
                "category",
                name="entitytype",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("entity_id", sa.String(length=96), nullable=True),
        sa.Column("source_id", sa.String(length=96), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("blocks", sa.Text(), nullable=True),
        sa.Column("impact_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("owner_id", sa.String(length=96), nullable=True),
        sa.Column("first_seen_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("occurrence_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("is_blocking", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("data_gap", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_data_gap_dedup_key"), ["dedup_key"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_data_gap_entity_id"), ["entity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_data_gap_first_seen_ts"), ["first_seen_ts"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_data_gap_kind"), ["kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_data_gap_last_seen_ts"), ["last_seen_ts"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_data_gap_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_data_gap_source_id"), ["source_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_data_gap_status"), ["status"], unique=False
        )

    op.create_table(
        "dim_user",
        sa.Column("user_id", sa.String(length=96), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "viewer",
                "analyst",
                "owner",
                "admin",
                "share_viewer",
                name="userrole",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("team", sa.String(length=96), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    with op.batch_alter_table("dim_user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dim_user_role"), ["role"], unique=False)

    op.create_table(
        "edition",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("edition_key", sa.String(length=64), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "live",
                "morning",
                "afternoon",
                name="editionkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "live",
                "frozen",
                "superseded",
                "failed",
                name="editionstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), server_default="1", nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trading_date", sa.String(length=10), nullable=False),
        sa.Column("theme_map_version", sa.Integer(), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.Column(
            "superseded_by_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("edition_key", "revision", name="uq_edition_key_revision"),
    )
    with op.batch_alter_table("edition", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_edition_as_of"), ["as_of"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_edition_edition_key"), ["edition_key"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_edition_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_edition_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_edition_trading_date"), ["trading_date"], unique=False
        )

    op.create_table(
        "alert_action",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "alert_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum(
                "publish",
                "confirm",
                "claim",
                "release",
                "reassign",
                "note",
                "start_review",
                "action",
                "create_task",
                "defer",
                "mark_false_positive",
                "dismiss",
                "resolve",
                "evidence_appended",
                name="alertactiontype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "from_state",
            sa.Enum(
                "detected",
                "tentative",
                "published",
                "claimed",
                "in_review",
                "actioned",
                "resolved",
                "false_positive",
                "dismissed",
                name="alertstate",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_state",
            sa.Enum(
                "detected",
                "tentative",
                "published",
                "claimed",
                "in_review",
                "actioned",
                "resolved",
                "false_positive",
                "dismissed",
                name="alertstate",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("actor_id", sa.String(length=96), nullable=True),
        sa.Column(
            "actor_kind", sa.String(length=16), server_default="user", nullable=False
        ),
        sa.Column("from_owner_id", sa.String(length=96), nullable=True),
        sa.Column("to_owner_id", sa.String(length=96), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("defer_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extra_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["alert_id"], ["alert.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alert_action", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_alert_action_action"), ["action"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alert_action_actor_id"), ["actor_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alert_action_alert_id"), ["alert_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alert_action_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "edition_artifact",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "edition_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("artifact_kind", sa.String(length=32), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=True),
        sa.Column("storage_key", sa.String(length=512), nullable=True),
        sa.Column("content", sa.LargeBinary(), nullable=True),
        sa.Column("view_state_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["edition_id"], ["edition.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("edition_artifact", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_edition_artifact_edition_id"), ["edition_id"], unique=False
        )

    op.create_table(
        "edition_revision",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "edition_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("diff_json", sa.Text(), nullable=True),
        sa.Column(
            "supersedes_edition_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("created_by", sa.String(length=96), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["edition_id"], ["edition.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("edition_revision", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_edition_revision_edition_id"), ["edition_id"], unique=False
        )

    op.create_table(
        "research_task",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "alert_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "in_progress",
                "blocked",
                "done",
                "cancelled",
                name="researchtaskstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("owner_id", sa.String(length=96), nullable=True),
        sa.Column(
            "entity_type",
            sa.Enum(
                "asset",
                "pair",
                "pool",
                "venue",
                "issuer",
                "underlying",
                "perp_contract",
                "perp_venue",
                "theme",
                "category",
                name="entitytype",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("entity_id", sa.String(length=96), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=96), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["alert_id"], ["alert.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("research_task", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_research_task_alert_id"), ["alert_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_research_task_due_at"), ["due_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_research_task_entity_id"), ["entity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_research_task_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_research_task_status"), ["status"], unique=False
        )

    op.create_table(
        "dim_own_product",
        sa.Column("product_id", sa.String(length=96), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("product_type", sa.String(length=64), nullable=True),
        sa.Column("underlying_id", sa.String(length=96), nullable=True),
        sa.Column("listing_venue", sa.String(length=128), nullable=True),
        sa.Column("launched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["underlying_id"],
            ["dim_underlying.underlying_id"],
        ),
        sa.PrimaryKeyConstraint("product_id"),
    )
    with op.batch_alter_table("dim_own_product", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dim_own_product_underlying_id"),
            ["underlying_id"],
            unique=False,
        )

    op.create_table(
        "issuance_candidate",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("underlying_id", sa.String(length=96), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "watch",
                "screening",
                "feasibility",
                "proposal",
                "approved",
                "declined",
                "parked",
                name="candidatestage",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("owner_id", sa.String(length=96), nullable=True),
        sa.Column("demand_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("liquidity_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("competition_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("feasibility_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("counter_rationale", sa.Text(), nullable=True),
        sa.Column(
            "source_alert_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_alert_id"], ["alert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["underlying_id"],
            ["dim_underlying.underlying_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("underlying_id", name="uq_issuance_candidate_underlying"),
    )
    with op.batch_alter_table("issuance_candidate", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_issuance_candidate_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_issuance_candidate_stage"), ["stage"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_issuance_candidate_underlying_id"),
            ["underlying_id"],
            unique=False,
        )

    op.create_table(
        "theme_map",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("underlying_id", sa.String(length=96), nullable=False),
        sa.Column("theme_id", sa.String(length=96), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_by", sa.String(length=96), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["theme_id"],
            ["dim_theme.theme_id"],
        ),
        sa.ForeignKeyConstraint(
            ["underlying_id"],
            ["dim_underlying.underlying_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "underlying_id", "theme_id", "version", name="uq_theme_map_entry"
        ),
    )
    with op.batch_alter_table("theme_map", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_theme_map_theme_id"), ["theme_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_theme_map_underlying_id"), ["underlying_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_theme_map_version"), ["version"], unique=False
        )

    op.create_table(
        "candidate_gate_log",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "candidate_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "from_stage",
            sa.Enum(
                "watch",
                "screening",
                "feasibility",
                "proposal",
                "approved",
                "declined",
                "parked",
                name="candidatestage",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_stage",
            sa.Enum(
                "watch",
                "screening",
                "feasibility",
                "proposal",
                "approved",
                "declined",
                "parked",
                name="candidatestage",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "decision",
            sa.Enum(
                "advance",
                "hold",
                "decline",
                "park",
                name="candidatedecision",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("decided_by", sa.String(length=96), nullable=False),
        sa.Column("evidence_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["issuance_candidate.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("candidate_gate_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_candidate_gate_log_candidate_id"),
            ["candidate_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_candidate_gate_log_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "fact_launch_window_snapshot",
        sa.Column("asset_id", sa.String(length=96), nullable=False),
        sa.Column("window", sa.String(length=8), nullable=False),
        sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("listed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_volume", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("adjusted_volume", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("market_cap", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("liquidity_usd", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column("trade_count", sa.Integer(), nullable=True),
        sa.Column("venue_count", sa.Integer(), nullable=True),
        sa.Column(
            "market_session",
            sa.Enum(
                "rth",
                "pre",
                "ah",
                "closed_weekday",
                "closed_weekend",
                "closed_holiday",
                name="marketsession",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_carried_forward", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["dim_asset.asset_id"],
        ),
        sa.PrimaryKeyConstraint("asset_id", "window", "snapshot_ts"),
    )
    with op.batch_alter_table("fact_launch_window_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fact_launch_window_snapshot_listed_at"),
            ["listed_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_fact_launch_window_snapshot_market_session"),
            ["market_session"],
            unique=False,
        )

    op.create_table(
        "product_coverage",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("underlying_id", sa.String(length=96), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "live",
                "planned",
                "gap",
                "not_applicable",
                name="coveragestate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("product_id", sa.String(length=96), nullable=True),
        sa.Column("demand_value", sa.Numeric(precision=30, scale=8), nullable=True),
        sa.Column(
            "demand_scope",
            sa.Enum(
                "spot_market_cap",
                "spot_volume",
                "dex_liquidity",
                "perp_volume",
                "perp_oi",
                name="metricscope",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assessed_by", sa.String(length=96), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["dim_own_product.product_id"],
        ),
        sa.ForeignKeyConstraint(
            ["underlying_id"],
            ["dim_underlying.underlying_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("underlying_id", name="uq_product_coverage_underlying"),
    )
    with op.batch_alter_table("product_coverage", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_product_coverage_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_product_coverage_state"), ["state"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_product_coverage_underlying_id"),
            ["underlying_id"],
            unique=False,
        )

    with op.batch_alter_table("alert", schema=None) as batch_op:
        # server_default, not just a Python-side default: this column is NOT NULL and
        # the table already has rows. See the module docstring for why every one of
        # them lands on ``detected`` rather than ``published``.
        batch_op.add_column(
            sa.Column(
                "state",
                sa.Enum(
                    "detected",
                    "tentative",
                    "published",
                    "claimed",
                    "in_review",
                    "actioned",
                    "resolved",
                    "false_positive",
                    "dismissed",
                    name="alertstate",
                    native_enum=False,
                    length=32,
                ),
                server_default="detected",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "confirmation_count", sa.Integer(), server_default="1", nullable=False
            )
        )
        batch_op.add_column(sa.Column("owner_id", sa.String(length=96), nullable=True))
        batch_op.add_column(
            sa.Column("published_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("sla_due_ts", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("deferred_until", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "evidence_completeness", sa.Numeric(precision=5, scale=4), nullable=True
            )
        )
        batch_op.create_index(
            batch_op.f("ix_alert_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alert_published_at"), ["published_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alert_sla_due_ts"), ["sla_due_ts"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_alert_state"), ["state"], unique=False)

    with op.batch_alter_table("alert_evidence", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("counter_evidence_json", sa.Text(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "verification_status",
                sa.Enum(
                    "verified",
                    "partial",
                    "not_verified",
                    "stale",
                    "empty",
                    name="verificationstatus",
                    native_enum=False,
                    length=32,
                ),
                server_default="verified",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("version", sa.Integer(), server_default="1", nullable=False)
        )
        batch_op.add_column(sa.Column("revision_reason", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alert_evidence", schema=None) as batch_op:
        batch_op.drop_column("revision_reason")
        batch_op.drop_column("version")
        batch_op.drop_column("verification_status")
        batch_op.drop_column("counter_evidence_json")

    with op.batch_alter_table("alert", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alert_state"))
        batch_op.drop_index(batch_op.f("ix_alert_sla_due_ts"))
        batch_op.drop_index(batch_op.f("ix_alert_published_at"))
        batch_op.drop_index(batch_op.f("ix_alert_owner_id"))
        batch_op.drop_column("evidence_completeness")
        batch_op.drop_column("deferred_until")
        batch_op.drop_column("sla_due_ts")
        batch_op.drop_column("published_at")
        batch_op.drop_column("owner_id")
        batch_op.drop_column("confirmation_count")
        batch_op.drop_column("state")

    with op.batch_alter_table("product_coverage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_coverage_underlying_id"))
        batch_op.drop_index(batch_op.f("ix_product_coverage_state"))
        batch_op.drop_index(batch_op.f("ix_product_coverage_product_id"))

    op.drop_table("product_coverage")
    with op.batch_alter_table("fact_launch_window_snapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fact_launch_window_snapshot_market_session"))
        batch_op.drop_index(batch_op.f("ix_fact_launch_window_snapshot_listed_at"))

    op.drop_table("fact_launch_window_snapshot")
    with op.batch_alter_table("candidate_gate_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_gate_log_created_at"))
        batch_op.drop_index(batch_op.f("ix_candidate_gate_log_candidate_id"))

    op.drop_table("candidate_gate_log")
    with op.batch_alter_table("theme_map", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_theme_map_version"))
        batch_op.drop_index(batch_op.f("ix_theme_map_underlying_id"))
        batch_op.drop_index(batch_op.f("ix_theme_map_theme_id"))

    op.drop_table("theme_map")
    with op.batch_alter_table("issuance_candidate", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_issuance_candidate_underlying_id"))
        batch_op.drop_index(batch_op.f("ix_issuance_candidate_stage"))
        batch_op.drop_index(batch_op.f("ix_issuance_candidate_owner_id"))

    op.drop_table("issuance_candidate")
    with op.batch_alter_table("dim_own_product", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dim_own_product_underlying_id"))

    op.drop_table("dim_own_product")
    with op.batch_alter_table("research_task", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_research_task_status"))
        batch_op.drop_index(batch_op.f("ix_research_task_owner_id"))
        batch_op.drop_index(batch_op.f("ix_research_task_entity_id"))
        batch_op.drop_index(batch_op.f("ix_research_task_due_at"))
        batch_op.drop_index(batch_op.f("ix_research_task_alert_id"))

    op.drop_table("research_task")
    with op.batch_alter_table("edition_revision", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_edition_revision_edition_id"))

    op.drop_table("edition_revision")
    with op.batch_alter_table("edition_artifact", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_edition_artifact_edition_id"))

    op.drop_table("edition_artifact")
    with op.batch_alter_table("alert_action", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alert_action_created_at"))
        batch_op.drop_index(batch_op.f("ix_alert_action_alert_id"))
        batch_op.drop_index(batch_op.f("ix_alert_action_actor_id"))
        batch_op.drop_index(batch_op.f("ix_alert_action_action"))

    op.drop_table("alert_action")
    with op.batch_alter_table("edition", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_edition_trading_date"))
        batch_op.drop_index(batch_op.f("ix_edition_status"))
        batch_op.drop_index(batch_op.f("ix_edition_kind"))
        batch_op.drop_index(batch_op.f("ix_edition_edition_key"))
        batch_op.drop_index(batch_op.f("ix_edition_as_of"))

    op.drop_table("edition")
    with op.batch_alter_table("dim_user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dim_user_role"))

    op.drop_table("dim_user")
    with op.batch_alter_table("data_gap", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_data_gap_status"))
        batch_op.drop_index(batch_op.f("ix_data_gap_source_id"))
        batch_op.drop_index(batch_op.f("ix_data_gap_owner_id"))
        batch_op.drop_index(batch_op.f("ix_data_gap_last_seen_ts"))
        batch_op.drop_index(batch_op.f("ix_data_gap_kind"))
        batch_op.drop_index(batch_op.f("ix_data_gap_first_seen_ts"))
        batch_op.drop_index(batch_op.f("ix_data_gap_entity_id"))
        batch_op.drop_index(batch_op.f("ix_data_gap_dedup_key"))

    op.drop_table("data_gap")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_entity_kind"))
        batch_op.drop_index(batch_op.f("ix_audit_log_entity_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_log_actor_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_action"))

    op.drop_table("audit_log")
    # ### end Alembic commands ###
